---
- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: Start iptables on boot
  service:
    name: iptables
    state: started
    enabled: yes

- name: Restart and set NTP auto start on boot
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Restart and set SNMP auto start on boot
  service:
    name: snmpd
    state: started
    enabled: yes

- name: Reboot server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for server to come back
  local_action: wait_for port=22 host="{{ ansible_ssh_host | default(inventory_hostname) }}" search_regex=OpenSSH delay=10
